CREATE SCHEMA IF NOT EXISTS FF;

CREATE TABLE FF.PRICE (
  ID INTEGER PRIMARY KEY,
  BRAND_ID INTEGER NOT NULL,
  START_DATE TIMESTAMP NOT NULL,
  END_DATE TIMESTAMP NOT NULL,
  PRICE_LIST INTEGER ,
  PRODUCT_ID INTEGER,
  PRIORITY INTEGER NOT NULL,
  PRICE DECIMAL(10,2) NOT NULL,
  CURRENCY VARCHAR(10) NOT NULL
);